spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mariadb://localhost:3306/benchmark?createIfNotExists=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true
