spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mariadb://localhost:3306/benchmark?createIfNotExists=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: create-drop

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health,prometheus'
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
