name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: pipeline
          MYSQL_DATABASE: benchmark
          MYSQL_USER: pipeline
          MYSQL_PASSWORD: pipeline
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Get MariaDB container IP
      id: db_ip
      run: echo "::set-output name=IP_ADDRESS::$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mariadb)"
    - name: Build with Maven
      run: |
        export DATABASE_HOST=$IP_ADDRESS
        export DATABASE_PORT=3306
        export DATABASE_NAME=benchmark
        export DATABASE_USERNAME=pipeline
        export DATABASE_PASSWORD=pipeline
        mvn -B package --file pom.xml
